#
# Copyright 2025, Colias Group, LLC
# Copyright 2025 Proofcraft Pty Ltd
#
# SPDX-License-Identifier: BSD-2-Clause
#

# Ignore all files that are part of the website itself, they will get their own
# link check. Only put admin files such as README.md into the standard PR check.
files:
  - "/book/src/"
