#
# Copyright 2024, Colias Group, LLC
#
# SPDX-License-Identifier: BSD-2-Clause
#

[book]
title = "Using Rust in seL4 Userspace"
authors = ["Nick Spinale <nick.spinale@coliasgroup.com>"]
multilingual = false

[build]
build-dir = "build"

[preprocessor.x-preprocessor]
before = [ "links" ]

[output.html]
git-repository-url = "https://github.com/coliasgroup/seL4-rust-tutorial"
additional-css = ["assets/sel4-rust-tutorial.css"]
additional-js = ["assets/sel4-rust-tutorial.js"]
